env:
  es6: true
  node: true
  browser: true
  mocha: true
extends:
  - plugin:react/recommended
  - airbnb
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
plugins:
  - flowtype
  - flow-vars
  - react
globals:
  fetch: true
  SyntheticInputEvent: true
rules:
  semi:
    - error
    - never
  no-trailing-spaces: 0
  no-restricted-syntax: 0
  import/no-extraneous-dependencies: 0
  import/prefer-default-export: 0
  class-methods-use-this: 0
  react/prefer-stateless-function: 0
  react/jsx-filename-extension: 0
  react/sort-comp:
    - 1
    - order:
      - type-annotations
      - state
      - constructor
      - static-methods
      - lifecycle
      - everything-else
      - render
      groups:
        lifecycle:
          - displayName
          - statics
          - defaultProps
          - constructor
          - componentWillMount
          - componentDidMount
          - componentWillReceiveProps
          - shouldComponentUpdate
          - componentWillUpdate
          - componentDidUpdate
          - componentWillUnmount
          - /^on.+$/
          - everything-else
