defaults: &DEFAULT
  working_directory: ~/app.orangesys.io
  docker:
    - image: circleci/node:6
      environment:
        PROJECT_NAME: orangesys
        CLOUDSDK_COMPUTE_ZONE: asia-east1-c
        CLUSTER_NAME: orangesysio

version: 2.0

jobs:
  checkout_code:
    <<: *DEFAULT
    steps:
      - checkout
      - persist_to_workspace:
          paths:
            - .

  build_dependencies:
    <<: *DEFAULT
    steps:
      - attach_workspace:
          at: ~/app.orangesys.io
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: dependency-cache-{{ checksum "firebase-functions/package.json" }}
      - run:
          name: install app.orangesys.io functions
          command: npm run functions:install
      - run:
          name: install app.orangesys.io
          command: npm install --silent
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/app.orangesys.io/node_modules
      - save_cache:
          key: dependency-cache-{{ checksum "firebase-functions/package.json" }}
          paths:
            - ./firebase-functions/node_modules
      - persist_to_workspace:
          paths:
            - node_modules
      - persist_to_workspace:
          paths:
            - firebase-functions/node_modules

  npm_test:
    <<: *DEFAULT
    steps:
      - attach_workspace:
          at: ~/app.orangesys.io
      - attach_workspace:
          at: ~/app.orangesys.io/node_modules
      - attach_workspace:
          at: ~/app.orangesys.io/firebase-functions/node_modules
      - run:
          name: test app.orangesys.io
          command: |
            echo $NODEJS_ENV_DEV | base64 --decode -i > .env
            npm test
      - run:
          name: check functions
          command: npm run functions:check
      - run:
          name: test functions
          command: npm run functions:test
      - run:
          name: test webpack
          command: |
            export PATH="$(npm bin):$PATH"
            env $(cat .env | xargs) webpack -p --progress

  deploy:
    <<: *DEFAULT
    steps:
      - attach_workspace:
          at: ~/app.orangesys.io
      - attach_workspace:
          at: ~/app.orangesys.io/node_modules
      - attach_workspace:
          at: ~/app.orangesys.io/firebase-functions/node_modules
      - run:
          name: build with production
          command: |
            export PATH="$(npm bin):$PATH"
            echo $NODEJS_ENV_PROD | base64 --decode -i > .env
            env $(cat .env | xargs) webpack -p --progress
            firebase deploy --project "$FIREBASE_PROJECT" --token "$FIREBASE_TOKEN" --non-interactive
            firebase functions:config:set stripe.secret_key=$STRIPE_SECRET_KEY --project "$FIREBASE_PROJECT" --token "$FIREBASE_FUNCTIONS_TOKEN"
            firebase functions:config:set mail.mailjet_public_key=$MAILJET_PUBLIC_KEY --project "$FIREBASE_PROJECT" --token "$FIREBASE_FUNCTIONS_TOKEN"
            firebase functions:config:set mail.mailjet_private_key=$MAILJET_PRIVATE_KEY --project "$FIREBASE_PROJECT" --token "$FIREBASE_FUNCTIONS_TOKEN"
            firebase functions:config:set mail.from=$MAILJET_SENDER_ADDRESS --project "$FIREBASE_PROJECT" --token "$FIREBASE_FUNCTIONS_TOKEN"
            firebase functions:config:set mail.to=$MAILJET_SENDER_ADDRESS --project "$FIREBASE_PROJECT" --token "$FIREBASE_FUNCTIONS_TOKEN"
            firebase functions:config:set webhook.stripe_invoice=$WEBHOOK_STRIPE_INVOICE --project "$FIREBASE_PROJECT" --token "$FIREBASE_FUNCTIONS_TOKEN"
            npm run functions:build
            firebase deploy --only functions --project "$FIREBASE_PROJECT" --token "$FIREBASE_FUNCTIONS_TOKEN" --non-interactive
            curl -s -S -X POST --data-urlencode "payload={'channel': '#ops', 'text': ':earth_asia: :fire: release $CIRCLE_PROJECT_REPONAME (SHA1 $SHORT_HASH) completed (build $CIRCLE_BUILD_NUM)' }" $SLACK_OPS >/dev/null

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - build_dependencies:
          requires:
            - checkout_code
      - npm_test:
          requires:
            - checkout_code
            - build_dependencies
      - deploy:
          requires:
            - checkout_code
            - build_dependencies
            - npm_test
          filters:
            branches:
              only: release
