version: 2.0

jobs:
  checkout_code:
    working_directory: ~/app.orangesys.io
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run:
          command: ls -ashl
      - persist_to_workspace:
          root: .
          paths:
            - .
